builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/arnarg/plex_exporter/version.Version={{.Version}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: arm64
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64

dockers:
- goos: linux
  goarch: amd64
  ids:
  - plex_exporter
  image_templates:
  - granra/plex_exporter:amd64
  skip_push: false
  dockerfile: docker/Dockerfile.release

- goos: linux
  goarch: arm
  goarm: 7
  ids:
  - plex_exporter
  image_templates:
  - granra/plex_exporter:arm
  skip_push: false
  dockerfile: docker/Dockerfile.release

- goos: linux
  goarch: arm64
  ids:
  - plex_exporter
  image_templates:
  - granra/plex_exporter:arm64
  skip_push: false
  dockerfile: docker/Dockerfile.release

before:
  hooks:
    - go mod tidy

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

archives:
  - id: bin
    format: binary

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
