{
 "title": "Plex",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Plex status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"plex_exporter\"}"
    }
   ]
  },
  {
   "title": "Plex watch time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(plex_sessions_active_count[$__range])/count_over_time(plex_sessions_active_count[1m])"
    }
   ]
  },
  {
   "title": "Plex active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 1 },
   "targets": [
    { "expr": "plex_sessions_active_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Library sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_library_section_size_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Plex version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_server_info" }
   ]
  }
 ]
}